spring.application.name=Kuizu

# Local H2 Database Configuration
# This will be overridden when running in Docker with PostgreSQL
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

# Logging Configuration
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.jdbc.datasource=DEBUG
# EmailJS Configuration
emailjs.url=https://api.emailjs.com/api/v1.0/email/send
emailjs.service.id=service_k3kdi2d
emailjs.template.id=template_7310zze
emailjs.public.key=3FP76-cXsYkd8ZrNy
emailjs.private.key=7JV0RN-MYLC7GUG78Rcx6
